version: '3.4'
networks:
  dockerapi-dev:
    driver: bridge 
services: 
  nginx: 
    image: jackyma001/nginx
    depends_on: 
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    networks:
      - dockerapi-dev  
  frontend:
    image: jackyma001/mealfrontend
    restart: unless-stopped
    depends_on: 
      - backend
    networks:
      - dockerapi-dev  
  backend:
    image: jackyma001/mealbackend
    restart: unless-stopped
    environment:
      ConnectionStrings__DefaultConnection: Server=db;Port=5432;Database=meal;User Id=postgres;Password=areyouok
    depends_on: 
      - db
    networks:
      - dockerapi-dev  
  db:
    image: jackyma001/postgres:latest
    restart: always
    networks:
      - dockerapi-dev
    volumes:
      - db_volume:/var/lib/postgresql/data/
volumes:
  db_volume: