version: '3.4'
networks:
  dockerapi-dev:
    driver: bridge 
services: 
  frontend:
    image: mealfrontend
    ports:
      - 80:80
    build: 
      context: frontend
      dockerfile: Dockerfile
      args:
          VUE_APP_API_URL: 

    depends_on: 
      - backend
    networks:
      - dockerapi-dev  
  backend:
    image: mealbackend
    build: 
      context: backend
      dockerfile: Dockerfile
    volumes:
          - ./backend/photos:/app/photos
    environment:
      ConnectionStrings__DefaultConnection: Server=db;Port=5432;Database=meal;User Id=postgres;Password=areyouok
    depends_on: 
      - db
    networks:
      - dockerapi-dev  
  db:
    image: jackyma001/postgres:latest
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "areyouok"
      POSTGRES_DB: "meal"
    networks:
      - dockerapi-dev
    volumes:
      - db_volume:/var/lib/postgresql/data/
volumes:
  db_volume: