version: '3.4'
networks:
  dockerapi-dev:
    driver: bridge 
services: 
  nginx: 
    image: nginx:1.17.10
    depends_on: 
      - frontend
      - backend
    networks:
      - dockerapi-dev  
    ports:
      - 80:80
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    image: mealfrontend
    restart: unless-stopped
    build: 
      context: frontend
      dockerfile: Dockerfile
      args:
          VUE_APP_API_URL: http://localhost
    ports: 
      - "8080:80"
    depends_on: 
      - backend
    networks:
      - dockerapi-dev  
  backend:
    image: mealbackend
    restart: unless-stopped
    build: 
      context: backend
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Server=db;Port=5432;Database=meal;User Id=postgres;Password=areyouok
    ports: 
      - "7372:80"
      - "7373:443"
    depends_on: 
      - db
    networks:
      - dockerapi-dev  
    volumes:
      - ./backend/photos:/app/photos
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data/
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "areyouok"
      POSTGRES_DB: "meal"
    networks:
      - dockerapi-dev
volumes:
  db_volume:
  dbscripts: