version: '3.4'
services: 
  nginx: 
    restart: always
  frontend:
    restart: always
    environment:
      API_RUL:${API_URL} 
  backend:
    environment:
      ConnectionStrings__DefaultConnection: Server=db;Port=5432;Database=meal;User Id=postgres;Password=areyouok
  db:
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "areyouok"
      POSTGRES_DB: "meal"