apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-backend
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: meal-backend
  template:
    metadata:
      labels:
        app: meal-backend
    spec:
      containers:
        - name: meal-backend
          image: jackyma001/mealbackend
          ports:
            - containerPort: 80 # Port your backend application listens on
          volumeMounts:
            - name: photos-volume
              mountPath: /app/photos
