name: Build & Push to DockerHub
on:
  push:
    branches:
      - 'main'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:frontend"
          push: true
          tags: jackyma001/mealfrontend:latest

      -
        name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: jackyma001/mealbackend:latest
  deploy:
      runs-on: ubuntu-latest
      needs: build_and_push

      steps:
        - name: Deploy to VPS via SSH action
          uses: appleboy/ssh-action@v0.1.3
          with:
            host: ${{ secrets.VPS_IP }}
            username: ${{ secrets.VPS_USERNAME }}
            password: ${{ secrets.VPS_PASSWORD }}
            port: 22
            script: |
              cd app
              docker-compose stop
              docker-compose rm -f
              docker-compose pull
              docker-compose up -d